@url_dev=http://localhost:4000
###  signup
POST {{url_dev}}/v1/api/shop/signup
Content-Type: application/json

{
    "name": "Shop Jangb315_6",
    "email": "dhuy2411_test12@gmail.com",
    "password": "123456"
}   

### signIn
POST {{url_dev}}/v1/api/shop/signin
Content-Type: application/json

{
    "email": "dhuy2411_test12@gmail.com",
    "password": "123456"
}

### signOut
POST {{url_dev}}/v1/api/shop/signout
Content-Type: application/json
userId: 648eb9e790fbd2cd78b6d376
token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDhlYjllNzkwZmJkMmNkNzhiNmQzNzYiLCJlbWFpbCI6ImRodXkyNDExX3Rlc3QxMkBnbWFpbC5jb20iLCJpYXQiOjE2ODcxNTc3MzQsImV4cCI6MTY4NzMzMDUzNH0.PWG2NhUvPpSk7FgXRW6nBzCFVzz5rcYMVRV-xRGs0saO0c4R_yaItVTbz84q7PlS9TefBawZYFOd1MN1vlWIvrNN8DJs03DeYookcgE_5JL7oZxqJhoJiyu5XLA8bkufTb-lvAQgeMNRJqx4GNewbTijkt9WEbASRag4lUcPDsmIiiWKXvxbgOMq2h1pD-jxUCpyeJsAY6YD0GPN7TbNFX5YK43BAl-xwhG13CKuSTchwd7Z0VhCozExBwkRnuVNvm__zKTH4DlCLeCCuhcO-zCbu-WInXbR-qr2QIUdoAWPuxFL18VZ96y9RdTpCx6JF-8astYi6-J6bPbl_v4D9nltnkp8DXDawD8gui1KB9WCxWn4n9xg3UxBGrDbu-wqezcMUZvtUiJssJhiMYaZqu4b5neGQIiWfTmeWBpfqxJgSt5SR_Bc2QuzK5SNXWU7EjsgK7eUi-FsaKqppHnyYgYNEj_1p_gLhG5HlU5eJmTep7cedV36cGi1jbehM1qV3GxmBmnqdhHss9QZJfoiUt-iLC0KRIETByLcg0dqrx4cgvErGNVtmxUDEsW4oHl4YRMvfa7KTPJZgOM4Cn6tW9hh3OOa1_pJey0l9CoZ1KO6RUorONhKsLMwrbtao2s7dlGLpGf5vbUBbfCoSqacr4GQr6VokulRuxL9vw8wqD0

{}