@url_dev=http://localhost:4000
@id=64aab8428d9754d2a54cf6fb
###  create
POST {{url_dev}}/v1/api/product
Content-Type: application/json
user-id: 648eb9e790fbd2cd78b6d376
token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDhlYjllNzkwZmJkMmNkNzhiNmQzNzYiLCJlbWFpbCI6ImRodXkyNDExX3Rlc3QxMkBnbWFpbC5jb20iLCJpYXQiOjE2ODg2Mzg1OTMsImV4cCI6MTY4ODgxMTM5M30.On4hKgJbZtJ9p23cHzGtci0_RclzwwDdmtUeCslEyvqqCGTRMrLuvHm8i95xXhkNom9tPcgDRVdMh58Kc2hPZu5Hg43xVszMvZYXQhgbwSUql8aGshQ-pKczglKoNENJcMELUr3MKQKBTigwjJK32luTkd51SmmdEIm0Yk4sAg8Bg8Rb85y8u05s7uK0je5PbfIyAfOEDZG2Zn4TqjPfZMoQjMdjTw0TDVNrIfdcASn85wZTyuWIog7rwOqMhWRvF1GMNDdZmjudEf7ISgdomc8MKZDgf2rfwwp2Pcxi3ZZOddxeOSA4GRYv4c9t-GHzpUu_TTZgyD03owxPJ-8JQlxGdLQ9q4n3NwhtMc1FnLeVFOz8w9xN7A83RvporbAiafaMrOLyd1rSju6WG9Rrc48jNH_AneFxDrBaR9_AVRBWOTZRrCajvxC9HF56cE1FALX84Sa1g2AGkYwUX68DxGtPeRTdMLEQoPLce_B_22gcYzrZOzqaeOUckqXiSVJ1E8cR8AIasJ3fWnsC_OmqDadZ06MIzcjyEmwwFpnBtfRemoGaOdNugHRmOhyZ82VlsrFxtuxmW4WfN6qAhPrQEYd6GQW7XwpYDvLBRrf49KuIg5oRfRlG5pk3MMvafG7AuPr4asAnzFJxITnhCCwpXrGp0AF3DzpbVeTWAfe4lQ0

{
    "product_name": "Iphone 13",
    "product_thumb": "thumbbbb",
    "product_description": "Description....",
    "product_price": "20.000.000",
    "product_quantity": 100,
    "product_type": "Electronic",
    "product_attributes": {
        "model": "Pro - 256GB",
        "color": "Yellow"
    }
}

### Get Detal
GET {{url_dev}}/v1/api/product/{{id}}
Content-Type: application/json
user-id: 648eb9e790fbd2cd78b6d376
token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDhlYjllNzkwZmJkMmNkNzhiNmQzNzYiLCJlbWFpbCI6ImRodXkyNDExX3Rlc3QxMkBnbWFpbC5jb20iLCJpYXQiOjE2ODg2Mzg1OTMsImV4cCI6MTY4ODgxMTM5M30.On4hKgJbZtJ9p23cHzGtci0_RclzwwDdmtUeCslEyvqqCGTRMrLuvHm8i95xXhkNom9tPcgDRVdMh58Kc2hPZu5Hg43xVszMvZYXQhgbwSUql8aGshQ-pKczglKoNENJcMELUr3MKQKBTigwjJK32luTkd51SmmdEIm0Yk4sAg8Bg8Rb85y8u05s7uK0je5PbfIyAfOEDZG2Zn4TqjPfZMoQjMdjTw0TDVNrIfdcASn85wZTyuWIog7rwOqMhWRvF1GMNDdZmjudEf7ISgdomc8MKZDgf2rfwwp2Pcxi3ZZOddxeOSA4GRYv4c9t-GHzpUu_TTZgyD03owxPJ-8JQlxGdLQ9q4n3NwhtMc1FnLeVFOz8w9xN7A83RvporbAiafaMrOLyd1rSju6WG9Rrc48jNH_AneFxDrBaR9_AVRBWOTZRrCajvxC9HF56cE1FALX84Sa1g2AGkYwUX68DxGtPeRTdMLEQoPLce_B_22gcYzrZOzqaeOUckqXiSVJ1E8cR8AIasJ3fWnsC_OmqDadZ06MIzcjyEmwwFpnBtfRemoGaOdNugHRmOhyZ82VlsrFxtuxmW4WfN6qAhPrQEYd6GQW7XwpYDvLBRrf49KuIg5oRfRlG5pk3MMvafG7AuPr4asAnzFJxITnhCCwpXrGp0AF3DzpbVeTWAfe4lQ0

### Patch
PATCH {{url_dev}}/v1/api/product/{{id}}
Content-Type: application/json
user-id: 648eb9e790fbd2cd78b6d376
token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDhlYjllNzkwZmJkMmNkNzhiNmQzNzYiLCJlbWFpbCI6ImRodXkyNDExX3Rlc3QxMkBnbWFpbC5jb20iLCJpYXQiOjE2ODg2Mzg1OTMsImV4cCI6MTY4ODgxMTM5M30.On4hKgJbZtJ9p23cHzGtci0_RclzwwDdmtUeCslEyvqqCGTRMrLuvHm8i95xXhkNom9tPcgDRVdMh58Kc2hPZu5Hg43xVszMvZYXQhgbwSUql8aGshQ-pKczglKoNENJcMELUr3MKQKBTigwjJK32luTkd51SmmdEIm0Yk4sAg8Bg8Rb85y8u05s7uK0je5PbfIyAfOEDZG2Zn4TqjPfZMoQjMdjTw0TDVNrIfdcASn85wZTyuWIog7rwOqMhWRvF1GMNDdZmjudEf7ISgdomc8MKZDgf2rfwwp2Pcxi3ZZOddxeOSA4GRYv4c9t-GHzpUu_TTZgyD03owxPJ-8JQlxGdLQ9q4n3NwhtMc1FnLeVFOz8w9xN7A83RvporbAiafaMrOLyd1rSju6WG9Rrc48jNH_AneFxDrBaR9_AVRBWOTZRrCajvxC9HF56cE1FALX84Sa1g2AGkYwUX68DxGtPeRTdMLEQoPLce_B_22gcYzrZOzqaeOUckqXiSVJ1E8cR8AIasJ3fWnsC_OmqDadZ06MIzcjyEmwwFpnBtfRemoGaOdNugHRmOhyZ82VlsrFxtuxmW4WfN6qAhPrQEYd6GQW7XwpYDvLBRrf49KuIg5oRfRlG5pk3MMvafG7AuPr4asAnzFJxITnhCCwpXrGp0AF3DzpbVeTWAfe4lQ0

{
    "product_name": "Iphone 14 - ProMax",
    "product_attributes": {
        "model": "Pro - 128GB"
    }
}

###  Get Draft All
GET {{url_dev}}/v1/api/product/drafts/all
Content-Type: application/json
user-id: 648eb9e790fbd2cd78b6d376
token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDhlYjllNzkwZmJkMmNkNzhiNmQzNzYiLCJlbWFpbCI6ImRodXkyNDExX3Rlc3QxMkBnbWFpbC5jb20iLCJpYXQiOjE2ODcyNDU0MjIsImV4cCI6MTY4NzQxODIyMn0.i8K1sfo67U37qtFH0CXOx8JIUqbIjsGPT3s5xPY2CYVgGJN1Q6oThMLJ3ORGloCOzlyvpZdSwJ-sOegvHcb9sOWBp6Ff0AmILSPEJ2wOnC1JCRuMjsogMFqZsIFVcTh9wz5G0ODucZCW7w8jVmkmLNX_0R1s1pCkLJdW9QS-lneY0_qRwpEZdFyJzZPCL8zbKVs8BgwM6Vw2fhN_uSC5Vt9_KYaW72k_HLJy_hRW7q0MjKbphLgRUdEx0P-6ccRtRn7qrZhivP8QkqOTCFcRFlGEXYV9oyPBVhrYuJthMCcBjivrZEJrb9YQeIM30tyll1FmJuCX34YLOk7ysumvyPJM396A4OOfbB17nrYeYzWtE83iJKbWKiCMP-yfvqtznMg2O5ZwfEZH6Wp84F8NFORq6MV54Hes_f9Xyd0CfTI1OOecsQCaPWSH1QJxtNnJg_4tSJdR4tsLTkQu6Tc97oMokj1SUW8dCmzZptxVm2AWTZXrAa7pP82oxNpQpnUhNhWASRgqXGeZtBWSFQoJj7hwg3dN04KbhFuaT9DsKwXFPXeyw0cdjsqiHk3nj6ZPOZoTnkXrYmItUjArrOo5k3ml21Ky-PSBYxrk1-rHG7F2iGLHsTD6lgZf5QHzIl4h2lSJ8piShhBmLyn5IMB15I0XPn1uKFCWD2nJ_UExoXs

###  Get Draft All
GET {{url_dev}}/v1/api/product/all
Content-Type: application/json
